import type { Request, Response, NextFunction } from "express";
import type { BudgetTracker } from "../utils/budget";

const ADMIN_HEADER = "x-wdf-admin-token";

/** GET /budget — current month's usage & cap. */
export function createGetBudgetHandler(budget: BudgetTracker) {
  return function getBudget(_req: Request, res: Response): void {
    res.json(budget.usage());
  };
}

/**
 * POST /budget/reset — zero the counter and clear the tripped flag.
 *
 * Gated because budget-reset is a privileged operation: anyone who can hit
 * the backend can otherwise wipe spending caps. Accepted if either:
 *  - the request carries the admin token in `X-WDF-Admin-Token`, or
 *  - the request originates from loopback (127.0.0.1 / ::1) AND no admin
 *    token is configured via env (local-dev convenience).
 */
export function createResetBudgetHandler(budget: BudgetTracker) {
  return async function resetBudget(
    req: Request,
    res: Response
  ): Promise<void> {
    if (!authorizeReset(req, budget)) {
      res.status(403).json({
        error:
          "Forbidden. Provide the admin token in the X-WDF-Admin-Token header.",
        code: "admin_token_required",
      });
      return;
    }
    await budget.reset();
    res.json(budget.usage());
  };
}

/**
 * GET /admin/token — returns the *auto-generated* admin token so the
 * extension can fetch it on first run, *only* if it was generated by the
 * backend itself (never when the operator explicitly configured one via
 * env). This keeps the UX friction low for the single-user local-dev case
 * while still requiring a token in production.
 *
 * Gated to loopback to avoid leaking the token to arbitrary callers.
 */
export function createGetAdminTokenHandler(budget: BudgetTracker) {
  return function getAdminToken(req: Request, res: Response): void {
    if (!isLoopback(req)) {
      res.status(403).json({ error: "Forbidden." });
      return;
    }
    if (budget.hasEnvAdminToken()) {
      // If the operator set a real token, we don't hand it out — they should
      // copy it into the extension options themselves.
      res.status(404).json({
        error:
          "Admin token is configured via BUDGET_ADMIN_TOKEN; copy it into the extension options manually.",
        code: "env_managed",
      });
      return;
    }
    const token = budget.adminToken();
    if (!token) {
      res.status(503).json({ error: "Token not yet initialised." });
      return;
    }
    res.json({ token, source: "auto" });
  };
}

function authorizeReset(req: Request, budget: BudgetTracker): boolean {
  const supplied = headerValue(req, ADMIN_HEADER);
  const expected = budget.adminToken();
  if (supplied && expected && constantTimeEq(supplied, expected)) return true;
  // Loopback fallback is only allowed when the operator hasn't set an env
  // token at all. As soon as BUDGET_ADMIN_TOKEN is configured, we require
  // that header no matter what the source IP is — otherwise the env var
  // would be meaningless.
  if (!budget.hasEnvAdminToken() && !expected && isLoopback(req)) {
    return true;
  }
  return false;
}

function headerValue(req: Request, name: string): string | null {
  const v = req.headers[name];
  if (typeof v === "string") return v;
  if (Array.isArray(v)) return v[0] ?? null;
  return null;
}

function isLoopback(req: Request): boolean {
  // Express populates req.ip from trust-proxy settings; fall back to socket.
  const candidates = [
    req.ip,
    req.socket?.remoteAddress,
    (req.connection as { remoteAddress?: string } | undefined)?.remoteAddress,
  ].filter((s): s is string => typeof s === "string" && s.length > 0);
  for (const raw of candidates) {
    const addr = raw.replace(/^::ffff:/, ""); // unwrap IPv4-mapped IPv6
    if (addr === "127.0.0.1" || addr === "::1" || addr === "localhost") {
      return true;
    }
  }
  return false;
}

/** Length-aware, branchless string compare to avoid timing leaks. */
function constantTimeEq(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return diff === 0;
}

/**
 * Optional express middleware factory you can bolt in front of other
 * mutating routes if you add them later. Not used for GET /budget.
 */
export function requireAdminToken(budget: BudgetTracker) {
  return function middleware(
    req: Request,
    res: Response,
    next: NextFunction
  ): void {
    if (authorizeReset(req, budget)) {
      next();
      return;
    }
    res.status(403).json({
      error: "Forbidden. Provide the admin token in the X-WDF-Admin-Token header.",
      code: "admin_token_required",
    });
  };
}
